// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ReviewAnalyzerML.Model
{
    public class ModelInput
    {
        [ColumnName("feature"), LoadColumn(0)]
        public string Feature { get; set; }


        [ColumnName("0"), LoadColumn(1)]
        public bool Col0 { get; set; }


    }
}
